# 配置tomcat端口号
server:
  port: 9001

# 配置数据源
spring:
  application:
    name: user # (应用名称) 服务id
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.78:3306/smart_site?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

# 配置mybatis plus
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.xsysux
  configuration:
    map-underscore-to-camel-case: true

# 配置日志
logging:
  level:
    com.xsysux: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 配置eureka的服务地址
    register-with-eureka: true
    fetch-registry: true
  instance:
    ip-address: 127.0.0.1 # 配置ip地址
    prefer-ip-address: true # 更倾向于使用ip访问，不是host
    lease-renewal-interval-in-seconds: 30 # 服务续约(renew)的间隔时间，默认为30秒
    lease-expiration-duration-in-seconds: 90 # 服务失效时间，默认90秒


test:
  name: admin666
